
name: build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    uses: cc332030/maven/.github/workflows/build.yml@master
    with:
      java-version: 8
