
name: nexus

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  nexus:
    uses: cc332030/maven/.github/workflows/nexus.yml@master
    with:
      java-version: 8
      nexus-id: cc332030
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_SNAPSHOT_URL: ${{ secrets.NEXUS_SNAPSHOT_URL }}
      NEXUS_RELEASE_URL: ${{ secrets.NEXUS_RELEASE_URL }}
